nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'DELETE', 'PATCH', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-User-Data']
        expose_headers: ['Set-Cookie']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/': null
